package me.ibrahimrafi.wififileshare.server

private val extensionIconMapping = mapOf(
    "3gp" to "video.svg",
    "7z" to "archive.svg",
    "aac" to "audio.svg",
    "apk" to "package.svg",
    "appimage" to "package.svg",
    "avi" to "video.svg",
    "bak" to "database.svg",
    "bash" to "shell.svg",
    "bat" to "shell.svg",
    "bmp" to "image.svg",
    "ca-bundle" to "certificate.svg",
    "cda" to "audio.svg",
    "cer" to "certificate.svg",
    "com" to "shell.svg",
    "crt" to "certificate.svg",
    "css" to "css.svg",
    "csv" to "xsv.svg",
    "db" to "database.svg",
    "deb" to "deb.svg",
    "dll" to "shell.svg",
    "dmg" to "dmg.svg",
    "doc" to "document.svg",
    "docx" to "document.svg",
    "dpkg" to "deb.svg",
    "email" to "email.svg",
    "eml" to "email.svg",
    "eof" to "font.svg",
    "exe" to "package.svg",
    "flac" to "audio.svg",
    "flatpak" to "package.svg",
    "fodp" to "presentation.svg",
    "fods" to "worksheet.svg",
    "fodt" to "document.svg",
    "gif" to "image.svg",
    "gifv" to "video.svg",
    "go" to "go.svg",
    "gz" to "archive.svg",
    "heic" to "image.svg",
    "heif" to "image.svg",
    "htm" to "html.svg",
    "html" to "html.svg",
    "img" to "cd.svg",
    "iso" to "cd.svg",
    "jar" to "package.svg",
    "jks" to "key.svg",
    "jpeg" to "image.svg",
    "jpg" to "image.svg",
    "js" to "javascript.svg",
    "json" to "json.svg",
    "json5" to "json.svg",
    "jsonc" to "json.svg",
    "jsx" to "javascript.svg",
    "key" to "key.svg",
    "keystore" to "key.svg",
    "less" to "css.svg",
    "m4a" to "audio.svg",
    "m4v" to "video.svg",
    "mailbox" to "email.svg",
    "markdown" to "markdown.svg",
    "mbox" to "email.svg",
    "md" to "markdown.svg",
    "mdb" to "database.svg",
    "mdown" to "markdown.svg",
    "midi" to "audio.svg",
    "mjs" to "javascript.svg",
    "mkv" to "video.svg",
    "mov" to "video.svg",
    "mp3" to "audio.svg",
    "mp4" to "video.svg",
    "mpeg" to "video.svg",
    "mpg" to "video.svg",
    "msg" to "email.svg",
    "msi" to "package.svg",
    "mts" to "typescript.svg",
    "odp" to "presentation.svg",
    "ods" to "worksheet.svg",
    "odt" to "document.svg",
    "ogg" to "audio.svg",
    "otf" to "font.svg",
    "p12" to "key.svg",
    "pdf" to "pdf.svg",
    "pem" to "certificate.svg",
    "pfx" to "key.svg",
    "png" to "image.svg",
    "ppt" to "presentation.svg",
    "pptx" to "presentation.svg",
    "ps1" to "powershell.svg",
    "pub" to "key.svg",
    "py" to "python.svg",
    "pyc" to "python.svg",
    "pyo" to "python.svg",
    "rar" to "archive.svg",
    "rpm" to "package.svg",
    "rtf" to "document.svg",
    "sass" to "css.svg",
    "scss" to "css.svg",
    "sh" to "shell.svg",
    "so" to "shell.svg",
    "sql" to "sql.svg",
    "sqlite" to "database.svg",
    "svg" to "image.svg",
    "tar" to "archive.svg",
    "tiff" to "image.svg",
    "ts" to "typescript.svg",
    "tsv" to "xsv.svg",
    "tsx" to "typescript.svg",
    "ttf" to "font.svg",
    "txt" to "document.svg",
    "vob" to "video.svg",
    "wav" to "audio.svg",
    "webm" to "video.svg",
    "webp" to "image.svg",
    "wma" to "audio.svg",
    "woff" to "font.svg",
    "woff2" to "font.svg",
    "x509" to "certificate.svg",
    "xls" to "worksheet.svg",
    "xlsx" to "worksheet.svg",
    "xz" to "archive.svg",
    "zip" to "archive.svg",
    "zst" to "archive.svg",
)

internal fun iconForEntry(entry: DirectoryEntry): String {
    if (entry.isDirectory) return "directory.svg"

    val normalized = entry.name.trim()
    if (normalized.equals("README", ignoreCase = true) || normalized.equals("LICENSE", ignoreCase = true)) {
        return "scroll.svg"
    }

    val extension = entry.name.substringAfterLast('.', "").lowercase()
    return extensionIconMapping[extension] ?: "default.svg"
}
